using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
    [SerializeField]
    private float walkSpeed;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½x
    [SerializeField]
    private float runSpeed;//ï¿½ï¿½ï¿½é‘¬ï¿½x
    private float inputX, inputZ;//xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Azï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì“ï¿½ï¿½Í‚Ì•Û‘ï¿½
    private float distance;//ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½p

    [SerializeField]
    private float deceleration;//ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    [SerializeField]
    private float decelerationTime;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Êï¿½ï¿½ï¿½
    private float attenuation;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    private float decelerationCompaTime;//ï¿½ï¿½rï¿½pï¿½ï¿½ï¿½ï¿½
    private float decelerationReset;//ï¿½Ä“xï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½Ê‚ï¿½ï¿½ï¿½ï¿½ï¿½p
    [SerializeField]
    private ParticleSystem dashEffect;

    public static bool DASH;

    //Kikuchi
    [SerializeField]
    [Header("Playerã®è¦–ç·šæ–¹å‘")]
    private Transform crosshair;

    [SerializeField]
    private Transform player;
    
    public static GameObject PlayerGameObject;

    private Vector3 latestPos;  
    
    private PlayerAnim anim;

    [SerializeField]
    private SceneStartDelay CSD;

    void Awake()
    {
        PlayerGameObject = this.gameObject;
    }

    void Start()
    {
        attenuation = (1f - deceleration) / decelerationTime;//æ¸›é€Ÿã®è¨ˆç®—
        decelerationReset = deceleration * 1;
        decelerationCompaTime = 0;

        if(anim == null)
        {
            anim = GetComponent<PlayerAnim>();
        }

    }

    void Update()
    {
        if(!CSD.IsDelay || CthulhuManager.IsDead) return;
        MovePlayer();//ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ÌˆÚ“ï¿½ï¿½ï¿½ï¿½ï¿½
    }

    public void MovePlayer()
    {
        latestPos = this.transform.position; // ç§»å‹•å‰ã®åº§æ¨™
        //xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Azï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì“ï¿½ï¿½Í‚Ìæ“¾
        inputX = Input.GetAxis("Horizontal");//ï¿½ï¿½ï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        inputZ = Input.GetAxis("Vertical");//ï¿½ï¿½ï¿½ï¿½ï¿½Aï¿½cï¿½ï¿½ï¿½ï¿½
        //ï¿½Ú“ï¿½ï¿½ÌŒï¿½ï¿½ï¿½ï¿½È‚Ç‚Ìï¿½ï¿½Wï¿½Ö˜A
        Vector3 velocity = new Vector3(inputX, 0, inputZ);

        //ï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½ÌŒï¿½ï¿½ï¿½ï¿½Ìæ“¾
        Vector3 direction = velocity.normalized;

        //ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÌŒvï¿½Z
        if (Input.GetKey(KeyCode.LeftShift) || Input.GetKey(KeyCode.RightShift))
        {
            DASH = true;
            if (HpInvinciblyManager.IsDeceleration)
                distance = runSpeed * Time.deltaTime * deceleration;//ï¿½ï¿½ï¿½ï¿½
            else
                distance = runSpeed * Time.deltaTime;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            
        }
        else
        {
            DASH = false;
            if (HpInvinciblyManager.IsDeceleration)
                distance = walkSpeed * Time.deltaTime * deceleration;//ï¿½ï¿½ï¿½ï¿½
            else
                distance = walkSpeed * Time.deltaTime;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        }


        //æ¸›é€Ÿ
        if (HpInvinciblyManager.IsDeceleration)
        {
            //ï¿½ï¿½ï¿½Gï¿½ï¿½ï¿½ÔˆÈ“ï¿½ï¿½È‚ï¿½
            if (decelerationCompaTime < decelerationTime)
            {
                decelerationCompaTime += Time.deltaTime;
                deceleration += attenuation * 0.01f;
            }//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Êï¿½ï¿½ÔˆÈï¿½È‚ï¿½
            else if (decelerationCompaTime >= decelerationTime)
            {
                HpInvinciblyManager.IsDeceleration = false;//ï¿½ï¿½ï¿½ï¿½ğ–³‚ï¿½ï¿½ï¿½
                decelerationCompaTime = 0;//ï¿½ï¿½ï¿½Ô‚ï¿½ï¿½ï¿½ï¿½Zï¿½bï¿½g
                deceleration = decelerationReset;//ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½Ê‚ï¿½ï¿½ï¿½ï¿½ï¿½
            }
            if (deceleration >= 1) deceleration = 1;
        }

        //ï¿½Ú“ï¿½ï¿½ï¿½ÌŒvï¿½Z
        Vector3 destination = transform.position + direction * distance;


        if(DASH)
        {
            dashEffect.transform.rotation = Quaternion.Euler(direction.z * 90f,0f,-direction.x * 90f);
            dashEffect.Play();
        }
        else
            dashEffect.Stop(true, ParticleSystemStopBehavior.StopEmitting);



        //ï¿½Ú“ï¿½ï¿½ï¿½ÉŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‰ï¿½]
        //transform.LookAt(new Vector3(lookPos.position.x, 0f, lookPos.position.z));

        //æ­£é¢æ–¹å‘ã®è¨­å®š
        SetFoward();

        //ï¿½Ú“ï¿½ï¿½ï¿½Ìï¿½ï¿½Wï¿½Ìİ’ï¿½
        transform.position = destination;

        anim.PosAnimCheck(latestPos);
            
    }

    /// <summary>
    /// Playerã®æ­£é¢æ–¹å‘ã‚’Crosshiarã®æ–¹ã¸å‘ã‘ã‚‹
    /// </summary>
    public void SetFoward()
    {
        player.transform.rotation = Quaternion.FromToRotation(player.transform.forward,crosshair.transform.position - player.transform.position) * player.transform.rotation;
        this.transform.rotation = Quaternion.Euler(0.0f, player.transform.eulerAngles.y, 0.0f);
    }


}
